version: "3.8"

services:
  api_1:
    build: ./api
    ports:
      - "3333:3333"
    networks:
      - app-network
    restart: always

  api_2:
    build: ./api
    ports:
      - "3334:3333"
    networks:
      - app-network
    restart: always

  api_3:
    build: ./api
    ports:
      - "3335:3333"
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
